### ISSUE TITLE
Problem following installation instructions, dependency problem

### ISSUE THREAD

**Issue by danielhamngren** [Oslandia/workshop-jitenshea#2]
Hi,

I've been trying to follow the installation instruction in readme.md. There seems to be some kind of dependency problem. When I run the command 

`python setup.py install`

in my newly created virtual environment i get the following error:

`error: tornado 6.0.3 is installed but tornado<5,>=4.0 is required by {'luigi'}`

I think there is an issue with jupyter notebook depends on tornado 6 and therefore installs it first. 

I was able to reproduce the problem both on macOS and on Ubuntu 18.04. However I wasn't able to solve the problem.

**Comment by troopa81** [comment]
Hi,

Indeed there is some issues building the environment from scratch.

Best you can do if you are planning to attend the workshop in Bucharest
is to download the VM
[here](http://hekla.oslandia.net/workshop-jitenshea.ova) and launching
it with a recent VirtualBox version (6 or greater).

Everything is already installed, you just need to :
- login: login/mdp = osboxes.org/osboxes
- cd workshop-jitenshea
- source venv/bin/activate
- cd examples
- jupyter notebook

And the notebook should appear. Let me know if you get other issues.

**Comment by danielhamngren** [comment]
Thank you!

With the VM it works great. I'm looking forward to the workshop!

**Comment by delhomer** [comment]
@garaud any idea of what is going wrong there?

**Comment by garaud** [comment]
I can reproduce the issue with ubuntu 18.04 and python 3.6. I don't have the issue with a more recent version of python such as python 3.7.

I don't know why luigi requires a version of tornado less than 6.0.

I'm looking for it.

**Comment by garaud** [comment]
> I don't have the issue with a more recent version of python such as python 3.7.

I was wrong, I did.

**Comment by garaud** [comment]
The recent notebook version requires a version of tornado which seems incompatible to the version of tornado required by luigi.

Take a look at: https://github.com/spotify/luigi/commit/63007974de73444b06175e0163150023d58d4721

Maybe if we install luigi from the git instead of Pypi, it might work.

**Comment by garaud** [comment]
@danielhamngren you can remove your current virtualenv, update your local workshop Git repo and re-install the deps.

Tell us if it's fixed your issue.

Thanks
Dam
